# Generated by Django 2.1.5 on 2019-01-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destroyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destroyer',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
