# Generated by Django 2.1.5 on 2019-01-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destroyer', '0003_remove_destroyer_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destroyer',
            name='input',
        ),
        migrations.RemoveField(
            model_name='destroyer',
            name='language',
        ),
        migrations.RemoveField(
            model_name='destroyer',
            name='output',
        ),
    ]
