# Generated by Django 2.1.5 on 2019-01-24 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destroyer', '0006_auto_20190124_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destroyer',
            name='initial_language',
        ),
        migrations.RemoveField(
            model_name='destroyer',
            name='input',
        ),
        migrations.RemoveField(
            model_name='destroyer',
            name='output',
        ),
    ]
